const FLAGS = {
    RUB: "🇷🇺",
    USD: "🇺🇸",
    EUR: "🇪🇺",
    JPY: "🇯🇵",
    GBP: "🇬🇧",
    AUD: "🇦🇺",
    CAD: "🇨🇦",
    CHF: "🇨🇭",
    CNY: "🇨🇳",
    SEK: "🇸🇪",
    MXN: "🇲🇽",
    NZD: "🇳🇿",
    SGD: "🇸🇬",
    HKD: "🇭🇰",
    NOK: "🇳🇴",
    KRW: "🇰🇷",
    TRY: "🇹🇷",
    INR: "🇮🇳",
    BRL: "🇧🇷",
    ZAR: "🇿🇦",
    DKK: "🇩🇰",
    PLN: "🇵🇱",
    TWD: "🇹🇼",
    THB: "🇹🇭",
    MYR: "🇲🇾",
    KZT: "🇰🇿",
    BYN: "🇧🇾",
    AMD: "🇦🇲",
    GEL: "🇬🇪",
    UAH: "🇺🇦"

}
export { FLAGS }